coverage:
  range: 80..100
  round: down
  precision: 2
  ignore:
    - "**/*.pb.go"
    - "**/*.yml"
  status:
    project:
      default:
        enabled: yes
        target: 80


        threshold: null
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        enabled: no