version: '3.7'


x-environment: &default-env
    MONGO_INITDB_ROOT_USERNAME: devroot
    MONGO_INITDB_ROOT_PASSWORD: devroot
    MONGO_INITDB_DATABASE: challenge
    ME_CONFIG_MONGODB_SERVER: mongo
    ME_CONFIG_MONGODB_PORT: 27017
    ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    ME_CONFIG_MONGODB_AUTH_DATABASE: admin
    ME_CONFIG_MONGODB_ADMINUSERNAME: devroot
    ME_CONFIG_MONGODB_ADMINPASSWORD: devroot
    ME_CONFIG_BASICAUTH_USERNAME: dev
    ME_CONFIG_BASICAUTH_PASSWORD: dev

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      *default-env
    networks:
      - networks_todo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      *default-env
    networks:
      - networks_todo

  todod:
    hostname: todod
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION}
        BUILD_DATE: ${BUILD_DATE}
      target: release
    tty: true
    ports:
      - 8080:8080
    links:
      - mongo
    networks:
      - networks_todo

networks:
  networks_todo: