{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  name: {{ template "ws.fullname" . }}-ingress
spec:
  rules:
  - host: {{ template "ws.fullname" . }}.io
    http:
      paths:
      - path:
        backend:
          serviceName: {{ template "ws.fullname" . }}
          servicePort: grpc
  tls:
  - secretName: {{ template "ws.fullname" . }}-secret
    hosts:
      - {{ template "ws.fullname" . }}.io
{{- end }}
