apiVersion: v1
kind: Service
metadata:
  name: {{ template "ws.fullname" . }}
  labels:
    k8s-app: {{ template "ws.name" . }}
    chart: {{ template "ws.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  selector:
    k8s-app: {{ template "ws.name" . }}
  ports:
  - port: {{ .Values.service.grpcPort }}
    targetPort: {{ .Values.service.grpcPort }}
    name: grpc
  - port: {{ .Values.service.httpPort }}
    targetPort: {{ .Values.service.httpPort }}
    name: http