version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.4
      - image: circleci/mongo:3.4
    steps: # TODO we should see explicity the test, integration, ui test results
      - setup_remote_docker
      - run:
          name: Love Boat docker-compose and circleci
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - checkout
      - run:
          name: Install - requirements
          command: |
              make tools
              make dependencies
      - run:
          name: Test - run the test
          command: |
              make test
      - run:
          name: Integration Test - run the integration test
          command: |
              for i in `seq 1 10`;
              do
                nc -z localhost 27017 && echo Success && exit 0
                echo -n .
                sleep 10
              done
              echo Failed waiting for Mongo && exit 1
              make it-test
      - codecov/upload:
          file: ./target/coverage.txt



