replicaCount: 1
image:
  repository: sjeandeaux/todo
  tag: 0.4.0
  pullPolicy: Always

deployment:
  containerGRPCPort: 8080
  containerHTTPPort: 8081

service:
  grpcPort: 8080
  httpPort: 8081

mongodb:
  mongodbUsername: devroot
  mongodbPassword: devroot
  mongodbDatabase: challenge

# It uses https://github.com/kubernetes/ingress-nginx, you must have a certificate in {{ template "ws.fullname" . }}-secret
ingress:
  enabled: true
